// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: following_feeds.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const followNewFeed = `-- name: FollowNewFeed :one
INSERT INTO following_feeds (id, created_at, updated_at, user_id, feed_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, user_id, feed_id
`

type FollowNewFeedParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

func (q *Queries) FollowNewFeed(ctx context.Context, arg FollowNewFeedParams) (FollowingFeed, error) {
	row := q.db.QueryRowContext(ctx, followNewFeed,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i FollowingFeed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}

const returnUserFollowingFeeds = `-- name: ReturnUserFollowingFeeds :many
SELECT id, created_at, updated_at, user_id, feed_id FROM following_feeds WHERE user_id = $1
`

func (q *Queries) ReturnUserFollowingFeeds(ctx context.Context, userID uuid.UUID) ([]FollowingFeed, error) {
	rows, err := q.db.QueryContext(ctx, returnUserFollowingFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FollowingFeed
	for rows.Next() {
		var i FollowingFeed
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowFeed = `-- name: UnfollowFeed :exec
DELETE FROM following_feeds WHERE feed_id = $1 AND user_id = $2
`

type UnfollowFeedParams struct {
	FeedID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) UnfollowFeed(ctx context.Context, arg UnfollowFeedParams) error {
	_, err := q.db.ExecContext(ctx, unfollowFeed, arg.FeedID, arg.UserID)
	return err
}
